server:
  port: 8080
  tomcat:
    max-connections: 2000
    accept-count: 2000

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000

dyjava:
  beanId: dasdsadsad
  source-type: 1
  agents:
    - tenantId: 1
      clientKey: 213
      clientSecret: 123123
  forest:
    backend: okhttp3             # 后端HTTP框架（默认为 okhttp3）
    max-connections: 1000        # 连接池最大连接数（默认为 500）
    max-route-connections: 500   # 每个路由的最大连接数（默认为 500）
    max-request-queue-size: 500  # [自v1.5.22版本起可用] 最大请求等待队列大小
    max-async-thread-size: 300   # [自v1.5.21版本起可用] 最大异步线程数
    max-async-queue-size: 16     # [自v1.5.22版本起可用] 最大异步线程池队列大小
    timeout: 3000                # [已不推荐使用] 请求超时时间，单位为毫秒（默认为 3000）
    connect-timeout: 3000        # 连接超时时间，单位为毫秒（默认为 timeout）
    read-timeout: 3000           # 数据读取超时时间，单位为毫秒（默认为 timeout）
    max-retry-count: 3           # 请求失败后重试次数（默认为 0 次不重试）
    ssl-protocol: TLS            # 单向验证的HTTPS的默认TLS协议（默认为 TLS）
    log-enabled: true            # 打开或关闭日志（默认为 true）
    #log-request: true            # 打开/关闭Forest请求日志（默认为 true）
    #log-response-status: true    # 打开/关闭Forest响应状态日志（默认为 true）
    #log-response-content: false   # 打开/关闭Forest响应内容日志（默认为 false）
    #async-mode: platform         # [自v1.5.27版本起可用] 异步模式（默认为 platform）
  token-source-class: com.dyj.examples.service.RedisAgentTokenService
